on:
  push:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  VERSION: "1.1.${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Create a .NET Core class library project
        run: dotnet new classlib
        
      - name: Add NuGetPublish.cs
        run: echo 'public class NuGetPublish { public static void SayHello() { System.Console.WriteLine("Hello from ${{ github.repository }}!"); } }' > NuGetPublish.cs

      - name: Build package
        run: dotnet pack -p:RepositoryUrl=https://github.com/${{ github.repository }} -p:PackageVersion=${{ env.VERSION }}

      - name: Publish package
        run: dotnet nuget push bin/Debug/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - run: gh api repos/${{ github.repository_owner }}/nuget-install/dispatches <<< '{"event_type":"build"}' --input -
        if: ${{ env.REPO_TOKEN != null }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
